# Generated by Django 3.0.8 on 2020-08-05 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_student_sclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sgender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tgender',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='checkType',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sclass',
        ),
        migrations.AddField(
            model_name='teachplan',
            name='checkType',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
