# Generated by Django 3.0.8 on 2020-07-31 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('cId', models.AutoField(primary_key=True, serialize=False)),
                ('cName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('sgender', models.CharField(max_length=10)),
                ('sclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Grade')),
            ],
        ),
    ]
