# Generated by Django 3.0.8 on 2020-08-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('gain_date', models.DateField()),
            ],
            options={
                'db_table': 'achievement',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('textBook', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('gno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='TeachPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.FloatField()),
                ('teach_date', models.DateField()),
                ('checkType', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Course')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Grade')),
            ],
            options={
                'db_table': 'teachplan',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('jobTitle', models.CharField(max_length=10)),
                ('teachCourse', models.ManyToManyField(to='app1.Course')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('studentCourse', models.ManyToManyField(through='app1.Achievement', to='app1.Course')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='gradeCourses',
            field=models.ManyToManyField(through='app1.TeachPlan', to='app1.Grade'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Course'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Student'),
        ),
    ]
