from django.urls import path
from . import views
#从当前目录导入包
urlpatterns = [
    path('', views.hello,name="hello"),
    path('addGrades',views.addGrades,name="addGrades"),
    path('showGrades',views.showGrades,name="showGrades"),
    path("updateGrade",views.updateGrade,name="updateGrade"),
    path("delGrade",views.delGrade,name="delGrade"),
    path("addCourses",views.addCourses,name="addCourses"),
    path("showCourses",views.showCourses,name="showCourses"),
    path("updateCourse",views.updateCourse,name="updateCourse"),
    path("delCourse",views.delCourse,name="delCourse"),
    path("addTeachPlans",views.addTeachPlans,name="addTeachPlans"),
    path("showTeachPlans",views.showTeachPlans,name="showTeachPlans"),
    path("updateTeachPlan",views.updateTeachPlan,name="updateTeachPlan"),
    path("delTeachPlan",views.delTeachPlan,name="delTeachPlan"),
    path("addTeachers",views.addTeachers,name="addTeachers"),
    path("showTeachers",views.showTeachers,name="showTeachers"),
    path("updateTeacher",views.updateTeacher,name="updateTeacher"),
    path("delTeacher",views.delTeacher,name="delteacher"),
    path("addTeachings",views.addTeachings,name="addTeachings"),
    path("showTeachings",views.showTeachings,name="showTeachings"),
    path("updateTeaching",views.updateTeaching,name="updateTeaching"),
    path("delTeaching",views.delTeaching,name="delTeaching"),
    path("addStudents",views.addStudents,name="addStudents"),
    path("addStudentCourse",views.addStudentCourse,name="addStudentCourse"),
    path("showStudents",views.showStudents,name="showStudents"),
    path("updateStudent",views.updateStudent,name="updateStudent"),
    path("delStudent",views.delStudent,name="delStudent"),
    path("addAchievements",views.addAchievements,name="addAchievements"),
    path("showAchievements",views.showAchievements,name="showAchievements"),
    path("updateAchievement",views.updateAchievement,name="updateAchievement"),
    path("delAchievement",views.delAchievement,name="delAchievement"),
]